apiVersion: v1
kind: Service
metadata:
  name: color-frontend
  labels:
    app: color-frontend
    workload: color
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: http
  selector:
    app: color-frontend
