apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-backend-v1
  labels:
    app: color-backend
    workload: color
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: color-backend
      version: v1
  template:
    metadata:
      labels:
        app: color-backend
        workload: color
        version: v1
    spec:
      containers:
      - image: gcr.io/<REPLACE_WITH_YOUR_PROJECT_ID>/color-backend:v1
        name: goapp
        ports:
        - containerPort: 8080
